---
abstract: 'Client for AI::Ollama'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0'
  Test2::V0: '0'
  strict: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AI-Ollama-Client
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  File::ShareDir: '0'
  Future: '0'
  Future::Mojo: '0'
  Future::Queue: '0'
  Future::Utils: '0'
  Mojo::JSON: '0'
  Mojo::URL: '0'
  Mojo::UserAgent: '0'
  Mojolicious: '9'
  Moo: '2'
  OpenAPI::Modern: '0'
  PerlX::Maybe: '0'
  YAML::PP: '0'
  experimental: '0.031'
  perl: '5.020'
  stable: '0.031'
resources:
  bugtracker: https://github.com/Corion/AI-Ollama-Client/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/AI-Ollama-Client.git
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
