package AI::Ollama::PullModelResponse 0.01;
# DO NOT EDIT! This is an autogenerated file.
use 5.020;
use Moo 2;
use experimental 'signatures';

sub as_hash( $self ) {
    return { $self->%* }
}

=head2 C<< completed >>

Total bytes transferred.

=cut

has 'completed' => (
    is       => 'ro',
#   isa      => 'integer',
);

=head2 C<< digest >>

The model's digest.

=cut

has 'digest' => (
    is       => 'ro',
#   isa      => 'string',
);

=head2 C<< status >>

Status pulling the model.

=cut

has 'status' => (
    is       => 'ro',
#   isa      => 'string',
);

=head2 C<< total >>

Total size of the model.

=cut

has 'total' => (
    is       => 'ro',
#   isa      => 'integer',
);


1;
