package AI::Ollama::CreateModelResponse 0.01;
# DO NOT EDIT! This is an autogenerated file.

=head2 C<< status >>

Status creating the model

=cut

has 'status' => (
    is       => 'ro',
    isa      => 'string',
);


1;
