package AI::Ollama::GenerateEmbeddingResponse 0.01;
# DO NOT EDIT! This is an autogenerated file.

=head2 C<< embedding >>

The embedding for the prompt.

=cut

has 'embedding' => (
    is       => 'ro',
    isa      => 'array',
);


1;
