package AI::Ollama::Message 0.01;
# DO NOT EDIT! This is an autogenerated file.

=head2 C<< content >>

The content of the message

=cut

has 'content' => (
    is       => 'ro',
    isa      => 'string',
    required => 1,
);

=head2 C<< images >>

(optional) a list of Base64-encoded images to include in the message (for multimodal models such as llava)

=cut

has 'images' => (
    is       => 'ro',
    isa      => 'array',
);

=head2 C<< role >>

The role of the message

=cut

has 'role' => (
    is       => 'ro',
    isa      => 'string',
    required => 1,
);


1;
