package AI::Ollama::ModelInfo 0.01;
# DO NOT EDIT! This is an autogenerated file.

=head2 C<< license >>

The model's license.

=cut

has 'license' => (
    is       => 'ro',
    isa      => 'string',
);

=head2 C<< modelfile >>

The modelfile associated with the model.

=cut

has 'modelfile' => (
    is       => 'ro',
    isa      => 'string',
);

=head2 C<< parameters >>

The model parameters.

=cut

has 'parameters' => (
    is       => 'ro',
    isa      => 'string',
);

=head2 C<< template >>

The prompt template for the model.

=cut

has 'template' => (
    is       => 'ro',
    isa      => 'string',
);


1;
