package AI::Ollama::ModelsResponse 0.01;
# DO NOT EDIT! This is an autogenerated file.

=head2 C<< models >>

List of models available locally.

=cut

has 'models' => (
    is       => 'ro',
    isa      => 'array',
);


1;
