package AI::Ollama::PullModelResponse 0.01;
# DO NOT EDIT! This is an autogenerated file.

=head2 C<< completed >>

Total bytes transferred.

=cut

has 'completed' => (
    is       => 'ro',
    isa      => 'integer',
);

=head2 C<< digest >>

The model's digest.

=cut

has 'digest' => (
    is       => 'ro',
    isa      => 'string',
);

=head2 C<< status >>

Status pulling the model.

=cut

has 'status' => (
    is       => 'ro',
    isa      => 'string',
);

=head2 C<< total >>

Total size of the model.

=cut

has 'total' => (
    is       => 'ro',
    isa      => 'integer',
);


1;
